### ISSUE TITLE
salome_plugins.py Bugs

### ISSUE THREAD

**Issue by physici** [physici/ElmerSalome#14]
1. In Zeile 21 von muss statt else stehen:
    if not (os.path.exists(plugin_path + os.sep + "elmer_window_handler.py")):

**Comment by physici** [comment]
Kann ich nicht nachvollziehen, da die Zeile in Zeile 28 auftaucht:

```
# add SALOME_PLUGIN_PATH to Python environment for easier module import
if (os.environ.get("SALOME_PLUGINS_PATH") is not None):
    plugin_path = os.environ.get("SALOME_PLUGINS_PATH") +\
                  os.sep + "ElmerSalome"
else:
    # no environement variable so get path from current running file via inspect
    import inspect
    plugin_path = os.path.dirname(inspect.getfile(inspect.currentframe())) +\
                  os.sep + "ElmerSalome"

sys.path.append(plugin_path)

# if there is no elmer_window_handler.py in the directory
if not (os.path.exists(plugin_path + os.sep + "elmer_window_handler.py")):
    sys.exit("No Elmer module found")
```

**Comment by mzenker** [comment]
Bei mir steht aus irgendeinem Grund das Plugin nicht da, wo die Umgebungsvariable hinzeigt, deswegen brauche ich die explizite Prüfung, ob bei gesetzter Umgebungsvariable das plugin auch dort ist. Wenn man das erst in Zeile 28 merkt, ist es zu spät und das Ganze funktioniert nicht. 
Eigentlich könnte man doch auch auf die Variable verzichten und den Pfad gleich über den inspect-Mechanismus ermitteln oder?

**Comment by physici** [comment]
Ich habe jetzt die Überprüfung in beide Fälle direkt reingeschrieben. Damit sollte es jetzt gehen.

Die Umgebungsvariable müsste man theoretisch weglassen können. Bin mir aber da noch nicht 100% sicher. Es wäre auch denkbar, dass jemand die Module an einem anderen Ort speichert.

**Comment by mzenker** [comment]
Solange Salomé sie findet, sollte das doch egal sein - er holt sich ja den Ort, an dem die Datei steht, als plugin_path.
