### ISSUE TITLE
Store entered information

### ISSUE THREAD

**Issue by HoWilgh** [physici/ElmerSalome#26]
At least on Linux all entered Elmer- related information is not stored within the .hdf or as external file. This way all entered information is lost exiting Salome. 
Therefore, I request this feature.
BR,
HoWil

**Comment by physici** [comment]
The Elmer-module (Latest commit 2d4cd6d) is now able to read an existing sif-file and load the data in this file. 

After setup of a simulation, run the sif-file generator to store your settings. Reload them from the file when you want to continue. Saving the data in the .hdf-file is not possible.
