### ISSUE TITLE
Body properties / boundary properties editor action

### ISSUE THREAD

**Issue by physici** [physici/ElmerSalome#4]
In elmer these are shown after selection in the menu and double click on the corresponding surface.

In Salome this has to be connected to the selected item in the explorer window. Additionally, the event has to be triggered somehow? Menu entry? Or other?

**Comment by physici** [comment]
Currently realized via menu entry. Maybe it is possible to to use the context menu somehow.

**Comment by HoWilgh** [comment]
Maybe it is easier to set these properties only on e.g. Groups-of-Faces. They can be named properly and are needed for the (.unv) mesh generation and could be used via their names as described here....  http://www.elmerfem.org/forum/viewtopic.php?f=7&t=4220#p14925

**Comment by physici** [comment]
Using mesh names is obviously the only consistent way to get the boundary settings correctly. So it is used as of March '17
